### ISSUE TITLE
is_primary function throwing a null pointer exception

### ISSUE THREAD

**Issue by arthurcavallari** [alexcorvi/heic2any#8] opened 2020-02-12 01:45 UTC
I've found a couple of .heic images that break your script, I've attached them below.

For one of them, the is_primary function throws a null pointer exception, and the other file just complains format not supported.

[bad images.zip](https://github.com/alexcorvi/heic2any/files/4189442/bad.images.zip)

**Comment by alexcorvi** [comment] 2020-04-06 10:41
The zip file you gave had 3 heic images. One of them is actually already a `jpeg` image. To avoid such confusion I've added a code to detect whether the MimeType is already browser-consumable. The other two was caused by a bug.

This will be solved on the next release.

> [bad_images.zip](https://github.com/alexcorvi/heic2any/files/4437688/bad_images.zip) file `c.heic` is actually a jpeg with a misleading extension. file `a.heic` & `b.heic` is heic burst shots.

**Comment by alexcorvi** [comment] 2020-04-06 23:06
Fixed in `0.0.3`
[release note](https://github.com/alexcorvi/heic2any/releases/tag/0.0.3)

**Closed by alexcorvi** 2020-04-06 23:06 UTC
Labels: bug, next-release
